language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements-dev.txt
matrix:
  fast_finish: true
script:
- pytest
after_success:
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back)
- |
  if [ "$BUILD_LEADER" = "YES" ]; then
    if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
      python setup.py coverage && codecov
    fi
  fi
deploy:
  provider: pypi
  user: aguaclara
  password:
    secure: YxI4bY0vJu69uvXxkHgOx1WfBZbzBXAAzhflg5zWsGK32Y711KFIgGiAgtfux8777qmxD0N/m+88RoChRKMVCriYWSzzmPflyH2cOA2oUqaGXGtJMnBRA1X4rlfVw1ONnUOg09GqI/Bg1cusutB/heo3itS+XNAKsqgQ0hYuAvLkuk8skzFqa6XNCFLZ9E6XOteaek3G+AqTrrhWYipugw+1LTV6uakWXqt7XB80pOHB8KGSA/ZDFdMKl43+TzzWzcJjZWJkjVyEP2B4ax1KMliZ/1eY/Ltcf/vW0PMY/2B5xXsZvsQRonWNOfQt8WCVNjQnRGJB9WWiorbNfn75k9QHLCXQiOlgZ+6ZXURam5kyHkVuuBWVGp9JSav6RQwwIlKbbV3WqZx5LhDPhuiGOV10ENk/9TwUmnwf4KjtX9WjAmelVrjIxgjoLZt2Rm00YnfigtJ9aXuXdkA+CNI25OczoYZRkeZU8S5wCqf/jtIDRK/iWiBPtAYobAKBYpNXjjFA2KmTMEj1230OwTT9/4wTt9eVuj4MWNrLvs2gSTXjIzfrqe1mivOd7VQf/JV0Gm38ibbMhVmz/NU40y2/xVZnQG7oor9quJTL4c7q2VWvnG+5XX88RzGeaXTa7PSfTx9yQFbwor55Gvpl+aUAql863gqC/RgUPrxw2UNMtBE=
  on:
    branch: master
    tags: true
