name: Build

on: [pull_request]

jobs:
  test-python:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --python ${{ matrix.python-version }}
        
    - name: Run pytests and generate coverage report
      run: |
        pipenv run pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
  
  test-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        
    - name: Run doctests and build html files
      run: |
        cd docs
        pipenv run make doctest
        pipenv run make html

    - name: Run html-proofer
      uses: chabad360/htmlproofer@master
      with:
        directory: docs/build/html
        arguments: --allow_hash_href --ignore-files "docs/build/html/search.html"