name: Push or Pull Request

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run pytests and generate coverage report
      run: |
        pipenv run pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    
    - name: Run doctests
      run: |
        cd docs
        pipenv run make doctest
        pipenv run make html

    - name: Run html-proofer
      uses: chabad360/htmlproofer@master
        with:
          directory: "build/html"
          arguments: --allow_hash_href --file_ignore "build/html/search.html"